# -*- coding: utf-8 -*-
"""Meeting mins Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NC9J-rC0W9-rS25-nfAX07LNd6jNWjga
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

# User Inputs
meeting_title=input("Enter meeting title:")
date=input("Enter meeting date (DD-MM-YYYY):")
time=input("Enter meeting time:")
participants = input("Enter participants (comma separated):")
agenda = input("Enter agenda points (comma separated):")
decisions = input("Enter decisions taken (comma separated):")
action_items = input("Enter action items (comma separated):")
prepared_by = input("Prepared by: ")

# Process Inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip() ]
action_list = [a.strip() for a in action_items.split(",") if a.strip()]

# Create structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Paricipants": ",".join(participants_list),
    "Agenda": ",".join(agenda_list),
    "Decision Taken": ",".join(decisions_list),
    "Action Items": ",".join(action_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

# Convert to Dataframe
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting Minutes Generated Successfully\n")
display(df)

# Save as CSV
df.to_CSV("meeting_minutes.CSV", index=False)
print("\n File save as meeting_minutes.CSV")

Product Sales
12-02-2026
Frank,Melvin,George,Jenny
To hike the sales, increase the product quality
Taking the pure raw materials for the supplier, increasing the product quality
finalizing budgets, Schedule and follow-up