# -*- coding: utf-8 -*-
"""Text Generation code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyQGVm7Q8A8U37Jvus1h4CEgMcfiA9wL
"""

0.
!pip install transformers torch

from transformers import pipeline
#load text generation model(Gen AI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
#input prompt
prompt="Artificial Intelligece in finance will"

#Generate text
result=generator(prompt,
                 max_length=50,
                 num_return_sequences=1)
print("AI generated Text:")
print(result[0]["generated_text"])